CREATE USER IF NOT EXISTS faces@localhost IDENTIFIED BY 'faces';

DROP DATABASE IF EXISTS faces;
CREATE DATABASE faces;

GRANT ALL PRIVILEGES ON faces.* TO faces@localhost;

USE faces;

CREATE TABLE `cameras` (
    `id` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `x` FLOAT NOT NULL,
    `y` FLOAT NOT NULL,

    `rstp` VARCHAR(255) NOT NULL,

    `F` FLOAT DEFAULT 0,

    `current_frame` MEDIUMTEXT
);

CREATE TABLE `known_persons` (
    `id` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `picture` VARCHAR(255) NOT NULL,
    `embedding` MEDIUMTEXT
);

CREATE TABLE `occurrences` (
    `id` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `human_id` VARCHAR(255),
    `face_id` VARCHAR(255),
    `camera_id` INT NOT NULL,
    `timestamp` TIMESTAMP NOT NULL,
    `distance` FLOAT,

    `e1` FLOAT,
    `e2` FLOAT,
    `e3` FLOAT,
    `e4` FLOAT,
    `e5` FLOAT,
    `e6` FLOAT,
    `e7` FLOAT,
    `e8` FLOAT,
    `e9` FLOAT,
    `e10` FLOAT,
    `e11` FLOAT,
    `e12` FLOAT,
    `e13` FLOAT,
    `e14` FLOAT,
    `e15` FLOAT,
    `e16` FLOAT,
    `e17` FLOAT,
    `e18` FLOAT,
    `e19` FLOAT,
    `e20` FLOAT,
    `e21` FLOAT,
    `e22` FLOAT,
    `e23` FLOAT,
    `e24` FLOAT,
    `e25` FLOAT,
    `e26` FLOAT,
    `e27` FLOAT,
    `e28` FLOAT,
    `e29` FLOAT,
    `e30` FLOAT,
    `e31` FLOAT,
    `e32` FLOAT,
    `e33` FLOAT,
    `e34` FLOAT,
    `e35` FLOAT,
    `e36` FLOAT,
    `e37` FLOAT,
    `e38` FLOAT,
    `e39` FLOAT,
    `e40` FLOAT,
    `e41` FLOAT,
    `e42` FLOAT,
    `e43` FLOAT,
    `e44` FLOAT,
    `e45` FLOAT,
    `e46` FLOAT,
    `e47` FLOAT,
    `e48` FLOAT,
    `e49` FLOAT,
    `e50` FLOAT,
    `e51` FLOAT,
    `e52` FLOAT,
    `e53` FLOAT,
    `e54` FLOAT,
    `e55` FLOAT,
    `e56` FLOAT,
    `e57` FLOAT,
    `e58` FLOAT,
    `e59` FLOAT,
    `e60` FLOAT,
    `e61` FLOAT,
    `e62` FLOAT,
    `e63` FLOAT,
    `e64` FLOAT,
    `e65` FLOAT,
    `e66` FLOAT,
    `e67` FLOAT,
    `e68` FLOAT,
    `e69` FLOAT,
    `e70` FLOAT,
    `e71` FLOAT,
    `e72` FLOAT,
    `e73` FLOAT,
    `e74` FLOAT,
    `e75` FLOAT,
    `e76` FLOAT,
    `e77` FLOAT,
    `e78` FLOAT,
    `e79` FLOAT,
    `e80` FLOAT,
    `e81` FLOAT,
    `e82` FLOAT,
    `e83` FLOAT,
    `e84` FLOAT,
    `e85` FLOAT,
    `e86` FLOAT,
    `e87` FLOAT,
    `e88` FLOAT,
    `e89` FLOAT,
    `e90` FLOAT,
    `e91` FLOAT,
    `e92` FLOAT,
    `e93` FLOAT,
    `e94` FLOAT,
    `e95` FLOAT,
    `e96` FLOAT,
    `e97` FLOAT,
    `e98` FLOAT,
    `e99` FLOAT,
    `e100` FLOAT,
    `e101` FLOAT,
    `e102` FLOAT,
    `e103` FLOAT,
    `e104` FLOAT,
    `e105` FLOAT,
    `e106` FLOAT,
    `e107` FLOAT,
    `e108` FLOAT,
    `e109` FLOAT,
    `e110` FLOAT,
    `e111` FLOAT,
    `e112` FLOAT,
    `e113` FLOAT,
    `e114` FLOAT,
    `e115` FLOAT,
    `e116` FLOAT,
    `e117` FLOAT,
    `e118` FLOAT,
    `e119` FLOAT,
    `e120` FLOAT,
    `e121` FLOAT,
    `e122` FLOAT,
    `e123` FLOAT,
    `e124` FLOAT,
    `e125` FLOAT,
    `e126` FLOAT,
    `e127` FLOAT,
    `e128` FLOAT,

    `human_picture` VARCHAR(255) NOT NULL,
    `face_picture` VARCHAR(255),

    `picture_x` FLOAT NOT NULL,
    `picture_y` FLOAT NOT NULL
);